server:
  servlet:
    context-path: /api

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/sspk_ssdmd_pb
    username: postgres
    password: root
  jpa:
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
      hibernate.globally_quoted_identifiers: true

bot:
  name: sspk_ssdmd_PB_bot
    token: 5480993468:AAElm4mrYlSB2gG20mPBAvFu0OXb3nudG9w